name: build_app

on:
  push:
    tags: [ develop ]
  workflow_dispatch:

env:
  SCHEME: AltServer
  
jobs:
  master_deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
          
      - name: Set environment variables from project settings
        run: |
          function set-env-from-proj { 
            echo "$1=$(xcodebuild -scheme "AltServer" -showBuildSettings | grep " $1 " | sed "s/[ ]*$1 = //")" >> $GITHUB_ENV
          }
          set-env-from-proj FULL_PRODUCT_NAME
          set-env-from-proj INSTALL_PATH
          set-env-from-proj PRODUCT_BUNDLE_IDENTIFIER
          set-env-from-proj PRODUCT_MODULE_NAME
          set-env-from-proj PRODUCT_NAME
          set-env-from-proj PROJECT_NAME

      - name: Build and install app
        shell: bash
        run: |
          xcodebuild -scheme "$SCHEME" install DSTROOT=build/root | xcpretty

      - name: Package app
        run: |
          hdiutil create \
                  -fs HFS+ \
                  -srcfolder "build/root/$INSTALL_PATH/$FULL_PRODUCT_NAME" \
                  -volname "$PRODUCT_NAME" "build/$PRODUCT_MODULE_NAME.dmg"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: build/${{ env.PRODUCT_MODULE_NAME }}.dmg
