name: Build .app

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  workflow_dispatch:

env:
  SCHEME: AltServer

jobs:
  master_deploy:
    runs-on: macos-12

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: 14.2

      - name: Set environment variables from project settings
        run: |
          function set-env-from-proj {
            echo "$1=$(xcodebuild -scheme "AltServer" -showBuildSettings | grep " $1 " | sed "s/[ ]*$1 = //")" >> $GITHUB_ENV
          }
          set-env-from-proj FULL_PRODUCT_NAME
          set-env-from-proj INSTALL_PATH
          set-env-from-proj PRODUCT_BUNDLE_IDENTIFIER
          set-env-from-proj PRODUCT_MODULE_NAME
          set-env-from-proj PRODUCT_NAME
          set-env-from-proj PROJECT_NAME

      - name: Build and install app
        run: |
          xcodebuild -project AltStore.xcodeproj \
                      -scheme AltServer \
                      -sdk macosx \
                      install \
                      CODE_SIGNING_REQUIRED=NO \
                      AD_HOC_CODE_SIGNING_ALLOWED=YES \
                      CODE_SIGNING_ALLOWED=NO \
                      DEVELOPMENT_TEAM=XYZ0123456 \
                      ORG_IDENTIFIER=com.SideStore \
                      DSTROOT=build/root \
                      | xcpretty && exit ${PIPESTATUS[0]}

      - name: Package app
        run: |
          hdiutil create \
                  -fs HFS+ \
                  -srcfolder "build/root/$INSTALL_PATH/$FULL_PRODUCT_NAME" \
                  -volname "$PRODUCT_NAME" "build/$PRODUCT_MODULE_NAME.dmg"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: build/${{ env.PRODUCT_MODULE_NAME }}.dmg
